### Recuperar todos las peliculas
GET http://localhost:1234/movies

### Recuperar todas las peliculas de una categoria
GET http://localhost:1234/movies?genre=Action

### Recuperar todas las peliculas de una fecha
GET http://localhost:1234/movies?year=1994

### Recuperar todas las peliculas por multiples query
GET http://localhost:1234/movies?genre=drama&year=1994

### Recuperar una pelicula mediante el id
GET http://localhost:1234/movies/e1fc341f-2766-11ef-95c2-c46516b8f44f

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "Forrest Gump",
  "year": 1994,
  "director": "Robert Zemeckis",
  "duration": 142,
  "poster": "https://i.ebayimg.com/images/g/qR8AAOSwkvRZzuMD/s-l1600.jpg",
  "genre": [
    "Drama",
    "Romance"
  ],
  "rate": 8.8
}

### Borrar una película mediante el id
DELETE http://localhost:1234/movies/f4ef4094-2766-11ef-95c2-c46516b8f44f

### Actualizar una pelicula
PATCH http://localhost:1234/movies/e1fc36b5-2766-11ef-95c2-c46516b8f44f
Content-Type: application/json

{
  "rate": 9.3
}